[package]
name = "corrust_ui_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corrust_lib = {path = "../corrust_lib"}
eframe = "0.22.0"
egui = "0.22.0"
rfd = "0.11.4"
